name = "owenewans/adapter-socks5"
authors = ["Owen Ewans"]
license = "Unlicense"
package_version = "0.0.1"
wire_version = 1
classes = ["adapter"]
family = "socks5"
roles = ["client"]
entry = "lib/libsnolc_adapter_socks5.so"
toolchain = "1.98.1"
dependencies = []

[source]
revision = "83aadeda5c5ae26f27588b64b67a04b3584b31c6"

[build]
package = "snolc-adapter-socks5"

[[templates]]
role = "client"
source = "config/templates/modules/socks5.toml"
targets = ["x86_64-unknown-linux-gnu", "aarch64-linux-android", "armv7-linux-androideabi"]

[[platforms]]
target = "x86_64-unknown-linux-gnu"
roles = ["client"]
capabilities = ["connect", "udp-associate", "ipv4", "ipv6", "domain"]

[[platforms]]
target = "aarch64-linux-android"
roles = ["client"]
capabilities = ["connect", "udp-associate", "ipv4", "ipv6", "domain"]

[[platforms]]
target = "armv7-linux-androideabi"
roles = ["client"]
capabilities = ["connect", "udp-associate", "ipv4", "ipv6", "domain"]

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
minimum_isa = "x86-64"
minimum_libc = "2.28"
url = "https://github.com/owenewans/snolc/releases/download/v0.0.1/adapter-socks5-0.0.1-x86_64-unknown-linux-gnu.tar.gz"
byte_size = 309425
sha256 = "02b793a3756e0b833c7155796f8c8a31f2678246406740b7081350d44ffad87e"
build_output = "release/libsnolc_adapter_socks5.so"

[[artifacts]]
target = "aarch64-linux-android"
minimum_isa = "armv8-a"
minimum_android_api = 24
url = "https://github.com/owenewans/snolc/releases/download/v0.0.1/adapter-socks5-0.0.1-aarch64-linux-android.tar.gz"
byte_size = 305512
sha256 = "936b8860aceaed15b85d73619a0897c6f4a524647d22c0aea1ee54940b985da7"
build_output = "release/libsnolc_adapter_socks5.so"

[[artifacts]]
target = "armv7-linux-androideabi"
minimum_isa = "armv7-a"
minimum_android_api = 24
url = "https://github.com/owenewans/snolc/releases/download/v0.0.1/adapter-socks5-0.0.1-armv7-linux-androideabi.tar.gz"
byte_size = 274997
sha256 = "87831688ffddb82e096c6b4d2b92518083d01228d4cb39403612c4dc0c4b91cb"
build_output = "release/libsnolc_adapter_socks5.so"
