name = "owenewans/adapter-direct"
authors = ["Owen Ewans"]
license = "Unlicense"
package_version = "0.0.1"
wire_version = 1
classes = ["adapter"]
family = "direct"
roles = ["server"]
entry = "lib/libsnolc_adapter_direct.so"
toolchain = "1.98.1"
dependencies = []

[source]
revision = "83aadeda5c5ae26f27588b64b67a04b3584b31c6"

[build]
package = "snolc-adapter-direct"

[[templates]]
role = "server"
source = "config/templates/modules/direct.toml"
targets = ["x86_64-unknown-linux-gnu", "aarch64-linux-android", "armv7-linux-androideabi"]

[[platforms]]
target = "x86_64-unknown-linux-gnu"
roles = ["server"]
capabilities = ["connect", "dns", "tcp", "udp"]

[[platforms]]
target = "aarch64-linux-android"
roles = ["server"]
capabilities = ["connect", "dns", "tcp", "udp"]

[[platforms]]
target = "armv7-linux-androideabi"
roles = ["server"]
capabilities = ["connect", "dns", "tcp", "udp"]

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
minimum_isa = "x86-64"
minimum_libc = "2.28"
url = "https://github.com/owenewans/snolc/releases/download/v0.0.1/adapter-direct-0.0.1-x86_64-unknown-linux-gnu.tar.gz"
byte_size = 351773
sha256 = "5f8d1e45fe270fff29300d7de90e27099ab6708db23c1b593581dfcfece40d2b"
build_output = "release/libsnolc_adapter_direct.so"

[[artifacts]]
target = "aarch64-linux-android"
minimum_isa = "armv8-a"
minimum_android_api = 24
url = "https://github.com/owenewans/snolc/releases/download/v0.0.1/adapter-direct-0.0.1-aarch64-linux-android.tar.gz"
byte_size = 340019
sha256 = "5aa8b0d91523cd5c1ca9e71d42d398a39b25415e2abcb8995ec4b630499ea155"
build_output = "release/libsnolc_adapter_direct.so"

[[artifacts]]
target = "armv7-linux-androideabi"
minimum_isa = "armv7-a"
minimum_android_api = 24
url = "https://github.com/owenewans/snolc/releases/download/v0.0.1/adapter-direct-0.0.1-armv7-linux-androideabi.tar.gz"
byte_size = 311377
sha256 = "cf185497b538984bdf6f418ba47c750b0005135a24cedc35f38a5bc833e3f660"
build_output = "release/libsnolc_adapter_direct.so"
