name = "owenewans/adapter-socks5"
authors = ["Owen Ewans"]
license = "Unlicense"
package_version = "0.0.4"
wire_version = 1
classes = ["adapter"]
family = "socks5"
roles = ["client"]
entry = "lib/libsnolc_adapter_socks5.so"
toolchain = "1.98.1"
dependencies = []

[source]
revision = "5939b6f15deb0b966da97d6862b4ca1c9ebedc16"

[build]
package = "snolc-adapter-socks5"

[[templates]]
role = "client"
source = "config/templates/modules/socks5.toml"
targets = ["x86_64-unknown-linux-gnu", "aarch64-linux-android", "armv7-linux-androideabi"]

[[platforms]]
target = "x86_64-unknown-linux-gnu"
roles = ["client"]
capabilities = ["connect", "udp-associate", "ipv4", "ipv6", "domain"]

[[platforms]]
target = "aarch64-linux-android"
roles = ["client"]
capabilities = ["connect", "udp-associate", "ipv4", "ipv6", "domain"]

[[platforms]]
target = "armv7-linux-androideabi"
roles = ["client"]
capabilities = ["connect", "udp-associate", "ipv4", "ipv6", "domain"]

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
minimum_isa = "x86-64"
minimum_libc = "2.28"
url = "https://github.com/owenewans/snolc-modules/releases/download/v0.0.4/adapter-socks5-0.0.4-x86_64-unknown-linux-gnu.tar.gz"
byte_size = 311569
sha256 = "79b137eac5e6c67089f2932aebb315661f7209cf4da426a4a643a194723bf852"
build_output = "release/libsnolc_adapter_socks5.so"

[[artifacts]]
target = "aarch64-linux-android"
minimum_isa = "armv8-a"
minimum_android_api = 24
url = "https://github.com/owenewans/snolc-modules/releases/download/v0.0.4/adapter-socks5-0.0.4-aarch64-linux-android.tar.gz"
byte_size = 304949
sha256 = "2751a265d603f1e914dd0152cc821ad72d85d8170b241aec9db56d174a82059c"
build_output = "release/libsnolc_adapter_socks5.so"

[[artifacts]]
target = "armv7-linux-androideabi"
minimum_isa = "armv7-a"
minimum_android_api = 24
url = "https://github.com/owenewans/snolc-modules/releases/download/v0.0.4/adapter-socks5-0.0.4-armv7-linux-androideabi.tar.gz"
byte_size = 274517
sha256 = "879c0dba2e35c3fa239b130f207af71d80196a72ed74dc3e525fe9a05d0e71d3"
build_output = "release/libsnolc_adapter_socks5.so"
