name = "owenewans/carrier-tcp"
authors = ["Owen Ewans"]
license = "Unlicense"
package_version = "0.0.1"
wire_version = 1
classes = ["carrier"]
family = "tcp"
roles = ["client", "server"]
entry = "lib/libsnolc_carrier_tcp.so"
toolchain = "1.98.1"
dependencies = []

[source]
revision = "83aadeda5c5ae26f27588b64b67a04b3584b31c6"

[build]
package = "snolc-carrier-tcp"

[[templates]]
role = "client"
source = "config/templates/modules/tcp-client.toml"
targets = ["x86_64-unknown-linux-gnu", "aarch64-linux-android", "armv7-linux-androideabi"]

[[templates]]
role = "server"
source = "config/templates/modules/tcp.toml"
targets = ["x86_64-unknown-linux-gnu", "aarch64-linux-android", "armv7-linux-androideabi"]

[[platforms]]
target = "x86_64-unknown-linux-gnu"
roles = ["client", "server"]
capabilities = ["connect", "listen", "tcp"]

[[platforms]]
target = "aarch64-linux-android"
roles = ["client", "server"]
capabilities = ["connect", "listen", "tcp"]

[[platforms]]
target = "armv7-linux-androideabi"
roles = ["client", "server"]
capabilities = ["connect", "listen", "tcp"]

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
minimum_isa = "x86-64"
minimum_libc = "2.28"
url = "https://github.com/owenewans/snolc/releases/download/v0.0.1/carrier-tcp-0.0.1-x86_64-unknown-linux-gnu.tar.gz"
byte_size = 339053
sha256 = "0f459202e22b87119faf3a2b35ecef06082f15d028e1a9017157a6b9be47da09"
build_output = "release/libsnolc_carrier_tcp.so"

[[artifacts]]
target = "aarch64-linux-android"
minimum_isa = "armv8-a"
minimum_android_api = 24
url = "https://github.com/owenewans/snolc/releases/download/v0.0.1/carrier-tcp-0.0.1-aarch64-linux-android.tar.gz"
byte_size = 327460
sha256 = "ef5a5a7fa7e763c72aadd1e236ad97ac6ebd7ac028581bfce9a043d2eb76b2cd"
build_output = "release/libsnolc_carrier_tcp.so"

[[artifacts]]
target = "armv7-linux-androideabi"
minimum_isa = "armv7-a"
minimum_android_api = 24
url = "https://github.com/owenewans/snolc/releases/download/v0.0.1/carrier-tcp-0.0.1-armv7-linux-androideabi.tar.gz"
byte_size = 293782
sha256 = "c07b33678ed1fbb4372c56d41c85560b897d5a388e4dadda2b7f9f0b92761568"
build_output = "release/libsnolc_carrier_tcp.so"
