name = "owenewans/protection-noise"
authors = ["Owen Ewans"]
license = "Unlicense"
package_version = "0.0.1"
wire_version = 1
classes = ["protection"]
family = "noise"
roles = ["client", "server"]
entry = "lib/libsnolc_protection_noise.so"
toolchain = "1.98.1"
dependencies = []

[source]
revision = "83aadeda5c5ae26f27588b64b67a04b3584b31c6"

[build]
package = "snolc-protection-noise"

[[templates]]
role = "client"
source = "config/templates/modules/noise-client.toml"
targets = ["x86_64-unknown-linux-gnu", "aarch64-linux-android", "armv7-linux-androideabi"]

[[templates]]
role = "server"
source = "config/templates/modules/noise.toml"
targets = ["x86_64-unknown-linux-gnu", "aarch64-linux-android", "armv7-linux-androideabi"]

[[platforms]]
target = "x86_64-unknown-linux-gnu"
roles = ["client", "server"]
capabilities = ["noise-nk", "confidentiality", "integrity", "peer-authentication"]

[[platforms]]
target = "aarch64-linux-android"
roles = ["client", "server"]
capabilities = ["noise-nk", "confidentiality", "integrity", "peer-authentication"]

[[platforms]]
target = "armv7-linux-androideabi"
roles = ["client", "server"]
capabilities = ["noise-nk", "confidentiality", "integrity", "peer-authentication"]

[[artifacts]]
target = "x86_64-unknown-linux-gnu"
minimum_isa = "x86-64"
minimum_libc = "2.28"
url = "https://github.com/owenewans/snolc/releases/download/v0.0.1/protection-noise-0.0.1-x86_64-unknown-linux-gnu.tar.gz"
byte_size = 394560
sha256 = "041d8dfac2e11d553fa849c3155c99a78660452ff446b125888c1f9b96bce8bb"
build_output = "release/libsnolc_protection_noise.so"

[[artifacts]]
target = "aarch64-linux-android"
minimum_isa = "armv8-a"
minimum_android_api = 24
url = "https://github.com/owenewans/snolc/releases/download/v0.0.1/protection-noise-0.0.1-aarch64-linux-android.tar.gz"
byte_size = 367961
sha256 = "85fed5799100f5163937a8a56160f2cbafa26aeef151b336760f238e23fa06f2"
build_output = "release/libsnolc_protection_noise.so"

[[artifacts]]
target = "armv7-linux-androideabi"
minimum_isa = "armv7-a"
minimum_android_api = 24
url = "https://github.com/owenewans/snolc/releases/download/v0.0.1/protection-noise-0.0.1-armv7-linux-androideabi.tar.gz"
byte_size = 358504
sha256 = "7057a3722602953d91f4ffcbb694faca3393ba3874a05a40a7171c3a5ad0d500"
build_output = "release/libsnolc_protection_noise.so"
