[package]
name = "snolc-adapter-tun"
description = "TUN adapter for snolc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
libc.workspace = true
serde.workspace = true
snolc-sdk.workspace = true
toml.workspace = true
